// <auto-generated />
using System;
using Infra.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250623165754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Core.Entities.Estabelecimento", b =>
                {
                    b.Property<int>("estabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("estabId"));

                    b.Property<string>("estabCategorias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("estabDescricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("estabLocal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("estabNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("estabId");

                    b.ToTable("estabelecimentos");
                });

            modelBuilder.Entity("Domain.Core.Entities.Pedido", b =>
                {
                    b.Property<int>("pedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("pedidoId"));

                    b.Property<DateTime>("pedidoData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("pedidoNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("pedidoQuantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("pedidoValor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("pedidoId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Domain.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Prop")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
